# Changes here will be overwritten by Copier
_commit: v0.3.5
_src_path: https://gitlab.softwareheritage.org/swh/devel/swh-py-template.git
description: Software Heritage graph service
distribution_name: swh-graph
have_cli: true
have_workers: false
package_root: swh/graph
project_name: swh.graph
python_minimal_version: '3.9'
readme_format: rst
