POM_PATH=java/pom.xml

java:
	mvn -f $(POM_PATH) compile assembly:single

java-doc:
	mvn -f $(POM_PATH) javadoc:javadoc

java-%:
	mvn -f $(POM_PATH) $*

protoc:
	python3 -m grpc_tools.protoc -I. --python_out=. --mypy_out=. --grpc_python_out=. swh/graph/rpc/*.proto

clean-java: java-clean

.PHONY: java clean-java
